services:
  postgres:
    image: postgres:17.2
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5433:${POSTGRES_PORT}'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  project_name:
    container_name: project_name
    #    command: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:8001 --worker-connections 1000 --keep-alive 10 main:app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    build: .
    volumes:
      - '.:/project_name'
    ports:
      - '8001:8001'
    depends_on:
      - postgres
      - rabbitmq
      - redis

  celery_worker:
    container_name: celery_worker
    build: .
    env_file: .env
    command: python -m celery -A celery_tasks.main worker --pool=solo --loglevel=info -E
    volumes:
      - '.:/expresso'
      - 'celery-state:/data'
    depends_on:
      - rabbitmq
      - redis

  celery_beat:
    container_name: celery_beat
    build: .
    env_file: .env
    command: python -m celery -A celery_tasks.main beat --loglevel=info
    volumes:
      - '/tmp:/tmp'
    depends_on:
      - rabbitmq
      - redis


  flower:
    container_name: flower
    image: mher/flower:latest
    build: .
    restart: always
    env_file: .env
    ports:
      - "5555:5555"
    command: celery -A celery_tasks.main flower --port=5555 --broker=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - celery_worker

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project_name

  redis:
    image: 'redis:7.4'
    restart: unless-stopped
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
#    ports:
#      - '${REDIS_PORT}:${REDIS_PORT}'
#    expose:
#      - '6379'
    volumes:
      - 'redis-data:/data'

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
  redis-data:
  celery-state:
