global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['space:8001']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
